#!/bin/sh

KERNEL=$(uname -r)
UPTIME=$(uptime -p 2>/dev/null || awk '{print $1 " seconds"}' < /proc/uptime)
CPU=$(awk -F: '/model name/ {print $2}' /proc/cpuinfo | head -n 1 | xargs)
USER=$(whoami)
DISTRIBUTION=$(awk -F= '/^PRETTY_NAME/ {gsub(/"/, "", $2); print $2}' /etc/os-release)
MEMORY=$(free -m | awk 'NR==2 {print $3, $2}')

USED_MEMORY_MB=$(echo "$MEMORY" | cut -d' ' -f1)
TOTAL_MEMORY_MB=$(echo "$MEMORY" | cut -d' ' -f2)

echo "System Information"
echo "------------------"
echo "OS: $DISTRIBUTION"
echo "User: $USER"
echo "Kernel: $KERNEL"
echo "Uptime: $UPTIME"
echo "CPU: $CPU"
echo "Memory: $USED_MEMORY_MB MiB / $TOTAL_MEMORY_MB MiB"
echo "Shell: $SHELL"
