#!/bin/sh

KERNEL=$(uname -r)
UPTIME=$(uptime -p 2>/dev/null || < /proc/uptime awk '{print $1 " seconds"}')
CPU=$(grep 'model name' /proc/cpuinfo | head -n 1 | cut -d ':' -f2 | xargs)
MEMORY=$(grep 'MemTotal' /proc/meminfo | awk '{print $2 / 1024 " MB"}')
USER=$(whoami)
DISTRIBUTION=$(grep '^PRETTY_NAME' /etc/os-release | cut -d '=' -f2 | tr -d '"')

echo "System Information"
echo "------------------"
echo "OS: $DISTRIBUTION"
echo "User: $USER"
echo "Kernel: $KERNEL"
echo "Uptime: $UPTIME"
echo "CPU: $CPU"
echo "Memory: $MEMORY"
echo "Shell: $SHELL"
